In [1]:
!pip install numpy

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr2)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
int64


In [6]:
arr2.shape

(2, 4)

In [7]:
arr3 = np.eye(2)

arr3

array([[1., 0.],
       [0., 1.]])

In [14]:
arr4 = np.arange(1, 10, 2)
arr5 = np.linspace(0, 4, 5)
arr6 = np.zeros((2, 3))
arr7 = np.ones((3, 2, 4))
arr8 = np.full((2, 3), 4)

print(arr4)
print("----------")
print(arr5)
print("----------")
print(arr6)
print("----------")
print(arr7)
print("----------")
print(arr8)

[1 3 5 7 9]
----------
[0. 1. 2. 3. 4.]
----------
[[0. 0. 0.]
 [0. 0. 0.]]
----------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
----------
[[4 4 4]
 [4 4 4]]


In [15]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]

print(my_list[3:])
print(my_list[:5])
print(my_list[2:6])

[4, 5, 6, 7, 8]
[1, 2, 3, 4, 5]
[3, 4, 5, 6]


In [17]:
print(my_list[-5:-2])
print(my_list[-5:1])

[4, 5, 6]
[]


In [21]:
arr = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
print(arr[1:3])
print("-------")
print(arr[:-1])
print("-------")
print(arr[::2])

[[ 5  6  7  8]
 [ 9 10 11 12]]
-------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [24]:
print(arr)
print("-------------")
print(arr[:, 1:3])
print("-------------")
print(arr[:, :-1])
print("-------------")
print(arr[:, ::2])
print("-------------")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
-------------
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
-------------
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
-------------


In [25]:
print(arr)
print("-------------")
print(arr[1:3, :-1])
print("-------------")
print(arr[2:, 1:3])
print("-------------")
print(arr[::2, ::2])
print("-------------")
print(arr[1::2, 1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-------------
[[ 5  6  7]
 [ 9 10 11]]
-------------
[[10 11]
 [14 15]]
-------------
[[ 1  3]
 [ 9 11]]
-------------
[[ 6  8]
 [14 16]]


In [26]:
# 배열 생성 함수
a = np.ones(4)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [1. 1. 1. 1.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
