In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!cp -r drive/MyDrive/Test/SKT/gym_examples /content

In [4]:
!pip install gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 7.8 MB/s eta 0:00:00


In [5]:
import gymnasium as gym
env = gym.make('gym_examples:gym_examples/Reversi-v0', render_mode='text')

In [6]:
obs, info = env.reset()

/usr/local/lib/python3.10/dist-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be uint8, actual type: int16
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


In [7]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . . . . . .
3 | . . . 1 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [8]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [9]:
obs, reward, done,_, info = env.step((2, 4))

/usr/local/lib/python3.10/dist-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be uint8, actual type: int16
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


In [10]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . 2 1 . . .
3 | . . . 2 1 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [11]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [12]:
obs, reward, done, _,info = env.step((2, 2))

In [ ]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . 2 . . . .
2 | . . 1 2 1 . . .
3 | . . . 2 1 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
player: 2 opponent: 1
<class 'str'>


In [13]:
info['action_mask']

array([[0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [14]:
obs, reward, done,_, info = env.step((0, 2))
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . 1 . . . . .
1 | . . . 1 . . . .
2 | . . 1 2 2 2 . .
3 | . . . 2 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [15]:
reward

-1